<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class BookingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bookings')->insert([
            // [
            //     'user_id' => 1,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 1,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 2,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 2,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 3,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 2,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 4,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 5,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 5,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 6,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 5,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 6,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 6,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 7,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 1,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 7,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            // [
            //     'user_id' => 1,
            //     'created_at' => Carbon::now(),
            //     'updated_at' => Carbon::now(),
            //     'car_id' => 8,
            //     'start_date' => Carbon::create(2025, 3, 1)->toDateString(),
            //     'end_date' => Carbon::create(2025, 3, 3)->toDateString(),
            //     'total_price' => 48888900,
            //     'user_give_back' => false,
            // ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2025, 3, 5)->toDateString(),
                'end_date' => Carbon::create(2025, 3, 9)->toDateString(),
                'created_at' => Carbon::create(2025, 3, 9)->toDateString(),
                'updated_at' => Carbon::create(2025, 3, 9)->toDateString(),
                'total_price' => 2000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2025, 2, 5)->toDateString(),
                'created_at' => Carbon::create(2025, 2, 5)->toDateString(),
                'updated_at' => Carbon::create(2025, 2, 5)->toDateString(),
                'end_date' => Carbon::create(2025, 2, 9)->toDateString(),
                'total_price' => 3000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2025, 1, 5)->toDateString(),
                'created_at' => Carbon::create(2025, 1, 5)->toDateString(),
                'updated_at' => Carbon::create(2025, 1, 5)->toDateString(),
                'end_date' => Carbon::create(2025, 1, 9)->toDateString(),
                'total_price' => 7000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 12, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 12, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 12, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 12, 9)->toDateString(),
                'total_price' => 4000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 11, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 11, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 11, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 11, 9)->toDateString(),
                'total_price' => 6000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 10, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 10, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 10, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 10, 9)->toDateString(),
                'total_price' => 5000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 9, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 9, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 9, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 9, 9)->toDateString(),
                'total_price' => 8000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 8, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 8, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 8, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 8, 9)->toDateString(),
                'total_price' => 8000000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 7, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 7, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 7, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 7, 9)->toDateString(),
                'total_price' => 7500000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 6, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 6, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 6, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 6, 9)->toDateString(),
                'total_price' => 3560000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 5, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 5, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 5, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 5, 9)->toDateString(),
                'total_price' => 5560000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
            [
                'user_id' => 1,
                'car_id' => 8,
                'start_date' => Carbon::create(2024, 4, 5)->toDateString(),
                'created_at' => Carbon::create(2024, 4, 5)->toDateString(),
                'updated_at' => Carbon::create(2024, 4, 5)->toDateString(),
                'end_date' => Carbon::create(2024, 4, 9)->toDateString(),
                'total_price' => 5560000,
                'user_give_back' => true,
                'browsing_status' => true,
                'admin_give_back' => true,
            ],
        ]);
    }
}
